version: "3.3"

services:
  traefik:
    image: traefik:v2.1
    networks:
      - traefik
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LETSENCRYPT_FOLDER}:/letsencrypt
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=false
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT}
      - --entrypoints.https.address=:${TRAEFIK_HTTPS_PORT}
      - --certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=http
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)
        - traefik.http.services.dashboard.loadbalancer.server.port=${TRAEFIK_DASHBOARD_PORT}
        - traefik.http.routers.dashboard.tls=true
        - traefik.http.routers.dashboard.tls.certresolver=letsencrypt

networks:
  traefik:
    external: true
